server:
  port: 9999
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1111/eureka
    fetch-registry: true
